---
name: Test python legacy

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

permissions: read-all

jobs:
  test_python_legacy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6 # zizmor: ignore[unpinned-uses]
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Remove python-version file since it will conflict with pyenv
        run: rm .python-version

      - name: Set the python version
        uses: LizardByte/actions/actions/setup_python@master # zizmor: ignore[unpinned-uses]
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: pip install asyncmock httpx[brotli] # Don't read it from requirements since uv dependencies required python >= 3.8

      - name: Run tests
        run: python -m unittest discover
